

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
server:
  port: 8081
mybatis-plus:
  mapper-locations: com/wentao/hmsmanager/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true